devise_jwt_secret_key: your_devise_jwt_secret_key

# for production:
aws:
  access_key_id: your_aws_access_key_id
  secret_access_key: your_aws_secret_access_key
  region: your_aws_region
  bucket: your_aws_bucket